export const SET_USERS_LIST = 'SAVE_USERS_LIST';
export const FETCH_USERS_LIST_FAILS = 'FETCH_USERS_LIST_FAILS';
export const SET_CONNECTED_USERS_LIST = 'SET_CONNECTED_USERS_LIST';
export const FETCH_CONNECTED_USERS_LIST_FAILS = 'FETCH_CONNECTED_USERS_LIST_FAILS';
export const FETCH_MESSAGES_FAILS = 'FETCH_MESSAGES_FAILS';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_CURRENT_USERCHAT = 'SET_CURRENT_USERCHAT';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_DISCONNECT = 'USER_DISCONNECT';

export const SET_USER_ID = 'SET_USER_ID';
